services:
  database:
    image: postgres
    container_name: arkad_db
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data